version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: shiftly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shiftly
      POSTGRES_PASSWORD: shiftly
      POSTGRES_DB: shiftly_dev
    ports:
      - "5432:5432"
    volumes:
      - shiftly_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: shiftly-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - shiftly_redis_data:/data

volumes:
  shiftly_pg_data:
  shiftly_redis_data:
